# base image - node:alpine
FROM node:18.19.0-alpine

# set the working directory to /app
WORKDIR ./app

# install ganache-cli globally
RUN npm install -g ganache-cli

# set the command ganache-cli -h 0.0.0.0 
# for docker ganache-cli host on 0.0.0.0
CMD ["ganache-cli","-m","ball captain resource submit lesson claim proud dignity artist grid buyer core","-h","0.0.0.0"]